name: core_network
description: Network connectivity checking and API retry utilities.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  connectivity_plus: ^6.1.1
