name: core_datetime
description: Date and time utilities for formatting, parsing, and comparisons.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
